version: '3'
services:
  user-auth:
    hostname: 'user-auth.example.com'
    build: .
    container_name: "user-auth"
    command: ./bin/wait-for-it/wait-for-it.sh db:27017 -- node node_modules/nodemon/bin/nodemon.js .
    env_file:
      - .env
    environment:
      - 'PORT_WEB=1337'
    expose:
      - '${PORT_WEB}'
    ports:
      - '${PORT_WEB}:${PORT_WEB}'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    depends_on:
     - db
    links:
      - db

  db:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: 'mongod --smallfiles --storageEngine wiredTiger --logpath=/dev/null' # --quiet