version: '3'
services:
  # https-portal:
  #   image: steveltn/https-portal:1
  #   ports:
  #     - '80:8080'
  #     - '443:8080'
  # #     - '3000:3000'
  #   links:
  #     - user-auth
  #   restart: always
  #   environment:
  #     DOMAINS: 'user-auth.example.com -> http://user-auth'
  #     # STAGE: 'production'
  #     # FORCE_RENEW: 'true'

  user-auth:
    hostname: 'user-auth.example.com'
    build: .
    container_name: "user-auth"
    command: ./bin/wait-for-it/wait-for-it.sh db:27017 -- node node_modules/nodemon/bin/nodemon.js .
    env_file:
      - .env
    environment:
      - 'PORT_WEB=3000'
    expose:
      - '${PORT_WEB}'
    ports:
      - '${PORT_WEB}:${PORT_WEB}'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    depends_on:
     - db
    links:
      - db

  db:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --storageEngine wiredTiger --logpath=/dev/null # --quiet